
 const Committees =[

    {
        key:1,
        Cimage:"../images/UNGA.png",
        Cname: "UNITED NATIONS GENERAL ASSEMBLY (UNGA)",
        Quote: "More than ever before in human history, we share a common destiny. We can master it only if we face it together. And that, my friends, is why we have the United Nations.",
        Quotespeaker :"Kofi Anan, 7th Secretary-General of the UN",
        Desc: " IEM MUN 2022 is delighted to bring to you the United Nations General Assembly (UNGA), the main policy making organ comprising all member states. Comprising all Member States, it provides a unique forum for multilateral discussion of the full spectrum of international issues covered by the Charter of the United Nations, Decisions on key issues like international peace and security, admitting new members and the UN budget, among others, are taken by the UNGA.",
        Agenda : "Shared responsibilities for the peaceful promotion of disarmament and subsequent capacity building measures through peaceful, equitable and sustainable societies leading to regional stability in West Asia1",
        GuideLine1 : "An agenda lists the items of business to be taken up during a meeting or session.[3] It may also be called a calendar.[4] A meeting agenda may be headed with the date, time and location of the meeting, followed by a series of points outlining the order in which the business is to be conducted. Steps on any agenda can include any type of schedule or order the group wants to follow. Agendas may take different forms depending on the specific purpose of the group and may include any number of the items.",
        Guideline2: "An agenda lists the items of business to be taken up during a meeting or session.[3] It may also be called a calendar.[4] A meeting agenda may be headed with the date, time and location of the meeting, followed by a series of points outlining the order in which the business is to be conducted. Steps on any agenda can include any type of schedule or order the group wants to follow. Agendas may take different forms depending on the specific purpose of the group and may include any number of the items.",
        Speaker1img: "../images/unga/AgnitraSaha.jpeg",
        Speaker1name: "Agnitra Saha",
        s1pos: "Co-Chairperson",
        Speaker2img: "../images/unga/SourodeepGhosh.jpeg",
        Speaker2name: "Sourodeep Ghosh",
        s2pos: "Co-Chairperson",
    },
    {
        key:2,
        Cimage:"../images/UNITAR.png",
        Cname: " UNITED NATIONS INSTITUTE FOR TRAINING AND RESEARCH",
        Quote:  " A superior man is modest in his speech, but exceeds in his actions",
        Quotespeaker :"Confucius",
        Desc: " IEM MUN 2022 is delighted to bring to you the United Nations General Assembly (UNGA), the main policy making organ comprising all member states. Comprising all Member States, it provides a unique forum for multilateral discussion of the full spectrum of international issues covered by the Charter of the United Nations, Decisions on key issues like international peace and security, admitting new members and the UN budget, among others, are taken by the UNGA.",
        Agenda : "Reviewing the use of ICTs in Peacekeeping Operations",
        GuideLine1 : "An agenda lists the items of business to be taken up during a meeting or session.[3] It may also be called a calendar.[4] A meeting agenda may be headed with the date, time and location of the meeting, followed by a series of points outlining the order in which the business is to be conducted. Steps on any agenda can include any type of schedule or order the group wants to follow. Agendas may take different forms depending on the specific purpose of the group and may include any number of the items.",
        Guideline2: "An agenda lists the items of business to be taken up during a meeting or session.[3] It may also be called a calendar.[4] A meeting agenda may be headed with the date, time and location of the meeting, followed by a series of points outlining the order in which the business is to be conducted. Steps on any agenda can include any type of schedule or order the group wants to follow. Agendas may take different forms depending on the specific purpose of the group and may include any number of the items.",
        Speaker1img: "../images/unitar/AyushBanerjee.jpeg",
        Speaker1name: "Ayush Banerjee",
        s1pos: "Chairperson",
        Speaker2img: "../images/unitar/RupazBhadra.jpg",
        Speaker2name: "Rupaz Bhadra",
        s2pos: "Vice Chairperson",
    },
    // {

    //      key:3,
    //     Cimage:"../images/IP.png",
    //     Cname: "INTERNATIONAL PRESS (IP)",
    //     Quote: "More than ever before in human history, we share a common destiny. We can master it only if we face it together. And that, my friends, is why we have the United Nations.",
    //     Quotespeaker :"Kofi Anan, 7th Secretary-General of the UN",
    //     Desc: " IEM MUN 2022 is delighted to bring to you the United Nations General Assembly (UNGA), the main policy making organ comprising all member states. Comprising all Member States, it provides a unique forum for multilateral discussion of the full spectrum of international issues covered by the Charter of the United Nations, Decisions on key issues like international peace and security, admitting new members and the UN budget, among others, are taken by the UNGA.",
    //     Agenda : "An agenda lists the items of business to be taken up during a meeting or session.[3] It may also be called a calendar.[4] A meeting agenda may be headed with the date, time and location of the meeting, followed by a series of points outlining the order in which the business is to be conducted. Steps on any agenda can include any type of schedule or order the group wants to follow. Agendas may take different forms depending on the specific purpose of the group and may include any number of the items.",
    //     GuideLine1 : "An agenda lists the items of business to be taken up during a meeting or session.[3] It may also be called a calendar.[4] A meeting agenda may be headed with the date, time and location of the meeting, followed by a series of points outlining the order in which the business is to be conducted. Steps on any agenda can include any type of schedule or order the group wants to follow. Agendas may take different forms depending on the specific purpose of the group and may include any number of the items.",
    //     Guideline2: "An agenda lists the items of business to be taken up during a meeting or session.[3] It may also be called a calendar.[4] A meeting agenda may be headed with the date, time and location of the meeting, followed by a series of points outlining the order in which the business is to be conducted. Steps on any agenda can include any type of schedule or order the group wants to follow. Agendas may take different forms depending on the specific purpose of the group and may include any number of the items.",
    //     // Speaker1img: "../images/noAvatar.png",
    //     // Speaker1name: "Lorem Ipsum",
    //     // Speaker2img: "../images/noAvatar.png",
    //     // Speaker2name: "Lorem Ipsum",
    // },
    { 
        key:4,
        Cimage:"../images/IC.png",
        Cname: "INDIAN CABINET MINISTRY OF FINANCE",
        Quote: "More than ever before in human history, we share a common destiny. We can master it only if we face it together. And that, my friends, is why we have the United Nations.",
        Quotespeaker :"Kofi Anan, 7th Secretary-General of the UN",
        Desc: " IEM MUN 2022 is delighted to bring to you the United Nations General Assembly (UNGA), the main policy making organ comprising all member states. Comprising all Member States, it provides a unique forum for multilateral discussion of the full spectrum of international issues covered by the Charter of the United Nations, Decisions on key issues like international peace and security, admitting new members and the UN budget, among others, are taken by the UNGA.",
        Agenda :" a) Discussion on setting up a structure of Financing and meeting the commitments under Sustainable development Goals in India, in the Post- Pandemic era. b) Use of UPI for Cross border Payments."        ,
        GuideLine1 : "An agenda lists the items of business to be taken up during a meeting or session.[3] It may also be called a calendar.[4] A meeting agenda may be headed with the date, time and location of the meeting, followed by a series of points outlining the order in which the business is to be conducted. Steps on any agenda can include any type of schedule or order the group wants to follow. Agendas may take different forms depending on the specific purpose of the group and may include any number of the items.",
        Guideline2: "An agenda lists the items of business to be taken up during a meeting or session.[3] It may also be called a calendar.[4] A meeting agenda may be headed with the date, time and location of the meeting, followed by a series of points outlining the order in which the business is to be conducted. Steps on any agenda can include any type of schedule or order the group wants to follow. Agendas may take different forms depending on the specific purpose of the group and may include any number of the items.",
        Speaker1img: "../images/ic/SapnilBiswas.jpg",
        Speaker1name: "Sapnil Biswas",
        s1pos: "Prime Minister of India",
        Speaker2img: "../images/ic/SuchetaSinghaRoy.jpeg",
        Speaker2name: "Sucheta Singha Roy",
        s2pos: "Cabinet Secretary",

    },
    {
         key:5,
        Cimage:"../images/UN.png",
        Cname: "UN OCEAN CONFERENCE",
        Quote: "We cannot have a healthy planet without a healthy ocean.Together, let us do our part to make a difference for the ocean and for ourselves” UN-Secretary" ,
        Quotespeaker :"Kofi Anan, 7th Secretary-General of the UN",
        Desc: " IEM MUN 2022 is delighted to bring to you the United Nations General Assembly (UNGA), the main policy making organ comprising all member states. Comprising all Member States, it provides a unique forum for multilateral discussion of the full spectrum of international issues covered by the Charter of the United Nations, Decisions on key issues like international peace and security, admitting new members and the UN budget, among others, are taken by the UNGA.",
        Agenda : "Addressing Marine Pollution.",
        GuideLine1 : "An agenda lists the items of business to be taken up during a meeting or session.[3] It may also be called a calendar.[4] A meeting agenda may be headed with the date, time and location of the meeting, followed by a series of points outlining the order in which the business is to be conducted. Steps on any agenda can include any type of schedule or order the group wants to follow. Agendas may take different forms depending on the specific purpose of the group and may include any number of the items.",
        Guideline2: "An agenda lists the items of business to be taken up during a meeting or session.[3] It may also be called a calendar.[4] A meeting agenda may be headed with the date, time and location of the meeting, followed by a series of points outlining the order in which the business is to be conducted. Steps on any agenda can include any type of schedule or order the group wants to follow. Agendas may take different forms depending on the specific purpose of the group and may include any number of the items.",
        Speaker1img: "../images/unOCean/ArunavaBanerjee.jpeg",
        Speaker1name: "Arunava Banerjee",
        s1pos: "Chairperson",
        Speaker2img: "../images/unOcean/SrotoswiniGhatak.jpg",
        Speaker2name: "Srotoswini Ghatak",
        s2pos: "Vice Chairperson",
    }


]

export default Committees